Introduccion
marcosrmartin/MTD_Server pull request #13
Opened 2023-10-01 00:54 UTC by marcosrmartin

- [x] AVANZAR: he redactado lo hecho en este PR en la documentación.

2023-10-01 00:55 UTC, marcosrmartin commented
He realizado los cambios comentados en #9, menos el de añadir el desarrollo ágil a la introducción, creo que tendría más sentido añadirlo en la descripción del problema junto con los objetivos.

2023-10-02 05:34 UTC, JJ commented
Los PRs deben estar siempre en un milestone y resolver uno o varios issues. Márcalos en el cuerpo del PR, no sólo en los mensajes de commit.

2023-10-06 09:39 UTC, JJ requested changes
Si esto es *toda* la introducción, me parece un poco escasa. Deberías dar una pista de
* para quién vas a resolver el problema (historias de usuario)
* qué objetivos tienes concretos dentro de la resolución de ese problema
* alguna pista sobre qué tipo de desarrollo vas a hacer. En capítulos posteriores ya aplicarás el tipo de desarrollo; por ejemplo, en planificación tendrás que planificar de acuerdo a lo que hayas elegido, pero en la intro tiene que comentarse si vas a usar ágil u otra cosa.

2023-10-06 09:39 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Para solucionar lo anterior, se introduce un concepto llamado \textit{moving target defense} (MTD de ahora en adelante), el cual se refiere a una estrategia de seguridad dinámica que implica cambiar
Cita para el concepto. Donde lo introdujeran o un resumen de trabajo reciente. Recuerda que #1 quiere referencias.

2023-10-06 09:40 UTC, JJ commented
> Los PRs deben estar siempre en un milestone y resolver uno o varios issues. Márcalos en el cuerpo del PR, no sólo en los mensajes de commit.

Y te recuerdo esto, ve trabajando siempre por milestones.

2023-10-06 16:53 UTC, marcosrmartin commented
Vuelvo a poner los objetivos, los quite aquí https://github.com/marcosrmartin/MTD_Server/pull/9#discussion_r1341986294, ya que entendía que eso era una sección. Los añado simplemente como un párrafo.

> He realizado los cambios comentados en #9, menos el de añadir el desarrollo ágil a la introducción, creo que tendría más sentido añadirlo en la descripción del problema junto con los objetivos.

En cuanto a citar la metodología, entiendo que no hay que explicarla, solo mencionarla. Lo hago al final de la introducción.

Por último, he modificados las HUs para añadir rol, ya que no los tenía definidos. En cuanto a esto, solamente he añadido investigadores a la introducción ya que es realmente a quien va dirigido

2023-10-09 07:06 UTC, JJ approved these changes
Sinceramente, no puedo poner ninguna pega; tiene todo lo que tiene que tener en el orden correcto. Lo que pasa es que mi experiencia me dice que a #1 no le suelen gustar los capítulos tan breves. Meter más morralla explicando qué es MTD puede ser, sin embargo, contraproducente (y también posiblemente mejor en un capítulo de estado del arte).

Si acaso, puedes poner un párrafo al final explicando cómo se va a organizar el resto de la memoria, y quizás un enlace al repo.

2023-10-09 15:10 UTC, marcosrmartin commented
Ok, he añadido el enlace al repo. En cuanto a la estructura, no lo voy a hacer ahora, porque no la tengo clara todavía, pero lo dejo como pendiente #22.

2023-10-09 15:22 UTC, merged