Estado del arte
marcosrmartin/MTD_Server pull request #14
Opened 2023-10-01 16:12 UTC by marcosrmartin

- [x] AVANZAR: he redactado lo hecho en este PR en la documentación.

2023-10-02 05:34 UTC, JJ commented
Exactamente igual, siempre debe haber un issue (podrías reabrir #4, asignándolo correctamente a una HU), y también un milestone.

2023-10-02 11:31 UTC, marcosrmartin commented
He utilizado directamente #5 que es el issue que salía de #4.

En cuanto a los milestones e issues sobre documentación, tengo una duda; la documentación (que entiendo que no es un PMV per se), ¿deben de añadirse a un milestone diferente, por ejemplo sobre implementación, o deben de tener su propio milestone? Cuando digo su propio milestone no se como enfocarlo si un milestone que sea introducción (y igual con el estado del arte) o uno que sea documentación donde se añaden todas las redacciones dentro.

2023-10-02 11:36 UTC, JJ commented
> He utilizado directamente #5 que es el issue que salía de #4.
> 
> En cuanto a los milestones e issues sobre documentación, tengo una duda; la documentación (que entiendo que no es un PMV per se), ¿deben de añadirse a un milestone diferente, por ejemplo sobre implementación, o deben de tener su propio milestone? Cuando digo su propio milestone no se como enfocarlo si un milestone que sea introducción (y igual con el estado del arte) o uno que sea documentación donde se añaden todas las redacciones dentro.

Claro que lo es, ¿por qué no va a serlo? Si tenemos #1, los productos que se le van a presentar están relacionados con al documentación.

Habrá milestones que sean solo documentación y presentación (los primeros y el último); en la implementación es mejor llevar los dos a la vez, la documentación y el trabajo.

2023-10-02 11:50 UTC, marcosrmartin commented
Ok, creo que estarían.

2023-10-06 09:45 UTC, JJ requested changes
Por favor, saca el capítulo de planificación de este PR y ponlo en otro PR aparte. Los PRs deben ser limitados en su ámbito y el capítulo de planificación ni siquiera lo mencionas en el título del PR; aparte de no corresponder al milestone, entiendo.

2023-10-06 09:45 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Este concepto se empieza a popularizar de forma teórica en informática (ya que no es exclusiva de esta) hace unos 10 años. Se han realizado investigaciones aplicándolo a diferentes ámbitos de la info
El texto debe contener todo el contexto que necesite. En este caso, no está claro a qué te refieres con "este"

2023-10-06 09:45 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Los MTD basados en servidores web no es una de las principales líneas de investigación, ya que son más difíciles de adaptar a un entorno de producción, no hay consenso sobre ellos y no han demostrado
no *son*. Quizás podrías incluir textidote para comprobar también la gramática.

2023-10-06 17:02 UTC, marcosrmartin commented on doc/secciones/03_estado_del_arte.tex
> +Los MTD basados en servidores web no es una de las principales líneas de investigación, ya que son más difíciles de adaptar a un entorno de producción, no hay consenso sobre ellos y no han demostrado
Lo tengo cuando se fusiona con la rama principal. En local utilizo LTeX – LanguageTool grammar/spell checking de VScode. A veces deja de funcionar, pero no es lo normal.

2023-10-09 09:33 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Los MTD basados en servidores web no es una de las principales líneas de investigación, ya que son más difíciles de adaptar a un entorno de producción, no hay consenso sobre ellos y no han demostrado
Lo puedes poner también cuando se abra un PR, y cuando se modifique. Si no pasa el test cuando se fusiona, tienes que abrir otro para arreglarlo. Es mejor que puedas corregir los tests en los PRs.

2023-10-23 16:04 UTC, merged