Planificacion
marcosrmartin/MTD_Server pull request #26
Opened 2023-10-11 17:10 UTC by marcosrmartin

- [x] AVANZAR: he redactado lo hecho en este PR en la documentación.

Se ha redactado los milestones, HUs utilizadas y metodología utilizada (además de hacer una breve descripción sobre estas).
También se ha realizado una estimación inicial de los costes.

2023-10-17 17:48 UTC, JJ requested changes
Para empezar, no estoy seguro que las historias de usuario tengan que ir en planificación; son la expresión de los deseos del usuario y es más habitual que vayan en la introducción. Pero el problema principal es que no parece que sigan el esquema habitual. Por favor, repiénsatelas.

2023-10-17 17:48 UTC, JJ commented on doc/bibliografia.bib
> +@misc{iv,
:rofl:

2023-10-17 17:48 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item [HU-2] Implementación MASS.
Una HU nunca puede ser *implemento esto*. Recuerda que es siempre un deseo del usuario en el dominio del problema.

2023-10-17 17:48 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item [M-x] Implementar MTD K8s en repositorio.
En desarrollo ágil es muy difícil predecir lo que se va  a hacer a 2 o 3milestones vista. Es mejor que estos los dejes para el capítulo de implementación.

2023-10-17 18:09 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item [HU-1] Adaptar el entorno a las implementaciones
Bueno, en GitHub también... Se trata de que #1 vea que efectivamente es lo que estás usando para el desarrollo.

2023-10-17 18:46 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item [HU-1] Adaptar el entorno a las implementaciones
También decía enlazarlo desde la memoria, poner el URL, vamos.

2023-10-18 20:39 UTC, marcosrmartin commented
@jj Listo para revisión, pero me surge la duda de, si se mueven las HUs y descripción del desarrollo ágil a la introducción, ¿no se quedaría este apartado prácticamente vacío?

2023-10-19 05:37 UTC, JJ commented
> @JJ Listo para revisión, pero me surge la duda de, si se mueven las HUs y descripción del desarrollo ágil a la introducción, ¿no se quedaría este apartado prácticamente vacío?

En la planificación tendrás que poner los primeros milestones y explicar un poco el desarrollo ágil para ver cómo se van a planificar los siguientes pasos; también explicar las herramientas que usas y demás y cómo te organizas dentro de un milestone.

2023-10-19 05:44 UTC, JJ requested changes
Algunos detalles a mejorar sobre colocación de ciertos contenidos y la introducción.
Quizás lo que puedes poner aquí de los costes es cuales son los costes *planificados*, pero tendrás que completar con los costes más o menos reales en su capítulo correspondiente.

2023-10-19 05:44 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\section{Desarrollo ágil}
Siempre debe haber una breve introducción al principio de cada capítulo poniéndolo en contexto y explicando de qué se va a hablar.

2023-10-19 05:44 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item \href{https://github.com/marcosrmartin/MTD_Server/milestone/1}{[M-0]} Preparar el entorno para la documentación.
Un milestone es un producto. No es "preparar", sino "producto de tal forma funcionando"

2023-10-19 05:44 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item \href{https://github.com/marcosrmartin/MTD_Server/milestone/2}{[M-2]} Implementación MASS.
Estos milestones pueden ir al capítulo de implementación. En este capítulo tendrás que explicar cómo el desarrollo ágil te ayuda a decidir qué hacer a continuación.

2023-10-19 05:44 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\section{Costes}
No sé si esto es "planificación"; me da la impresión de que sería mejor que fuera a implementación (porque es lo que estás usando para implementar)

2023-10-19 15:28 UTC, marcosrmartin commented on doc/secciones/04_planificacion.tex
> +\section{Costes}
Yo lo veo mejor aquí, ya que no es una implementación per se, para los benchmarks si que debería de mencionar el hardware y software más específico, pero no sus precios. Lo modificaré y le añadiré el *planificados*.

2023-10-23 07:08 UTC, JJ approved these changes
👍

2023-10-23 15:19 UTC, merged