Docker-images
marcosrmartin/MTD_Server pull request #41
Opened 2023-11-01 19:57 UTC by marcosrmartin

- [x] AVANZAR: he redactado lo hecho en este PR en la documentación.

Se ha elegido la imagen base de la que partir par la de los servidores y se han creado estas #38, ademas se ha añadido una página para comprobar que la configuración de los Dockerfiles es correcta.

2023-11-01 21:07 UTC, marcosrmartin commented
@JJ listo para revision

2023-11-02 10:25 UTC, JJ commented
Asigna a un milestone, por favor.

2023-11-02 10:27 UTC, JJ requested changes
Lo que estoy viendo es que el PR va un poco más allá de la elección de imagen base, incluyendo configuración de nginx y página base. Convendría que indicaras a qué issue corresponden, o lo saques en otro PR.

2023-11-02 13:52 UTC, JJ approved these changes
:+1: Si cambias un poco el título del PR, casi mejor.

2023-11-02 16:23 UTC, merged

2024-07-02 11:44 UTC, JJ reviewed
OK, voy a completar esto con issues.

2024-07-02 11:44 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\subsection{Imagen Docker para los servidores}
Creo que es más genérico "imagen OCI" o imagen de contenedores.

2024-07-02 11:44 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +El MTD deberá de rotar entre dos servidores, esto se llevará a cabo rotando dos contenedores Docker, uno que tendrá un servidor Nginx y otro uno Apache, está deberá ser la única diferencia sustancial
No sé yo, Marcos. Apache es más pesado, es otro tipo de servidor diferente a nginx.

2024-08-12 14:49 UTC, marcosrmartin commented on doc/secciones/06_implementacion.tex
> +El MTD deberá de rotar entre dos servidores, esto se llevará a cabo rotando dos contenedores Docker, uno que tendrá un servidor Nginx y otro uno Apache, está deberá ser la única diferencia sustancial
Esto era antes de hablar lo del cambio de TFG. Se que son distintos pero no voy a comparar entre ellos (al menos no para elegir uno sobre el otro). Simplemente son esos dos para poder comparar mis benchmarks a los de la investigacion original.